### ISSUE TITLE
--list-courses does not list courses in which the student is enrolled in: it lists some other cources not related to the account.

### ISSUE THREAD

**Issue by teicheld** [csyezheng/edx-dl#4]

**Comment by teicheld** [comment]
i was using the version provided py PyPi through pip. it was 0.6.4.

**Comment by teicheld** [comment]
if cloned from github everything works as expected and claims also to be version 0.6.4...
maybe doublecheck if the actual version is synced with PyPi.

**Comment by csyezheng** [comment]
Thanks for your feedback.
I re-uploaded the package to PyPI, the version is 0.6.5.
